name: ScoreboardPlus
version: 1.0
author: RayTraces
main: executed.scoreboard.ScoreboardPlus
description: Lightweight Scoreboard plugin with PlaceholderAPI Support!
website: https://taq5.online
depend: [PlaceholderAPI]